/**
 * Arabic descriptions for Airtable field Description (names stay snake_case English).
 * Applied via: node scripts/apply-airtable-ar-descriptions.mjs --apply
 */

export const FIELD_DESCRIPTIONS_AR = {
  Centers: {
    center_name: 'اسم المركز (لاتيني / رسمي للأنظمة)',
    center_name_ar: 'الاسم الرسمي للمركز بالعربية',
    center_code: 'رمز المركز الفريد (مثال: PRIV-MSK-01)',
    center_type: 'نوع المركز: خاص private أو حكومي government',
    shift_model: 'نموذج الدوام: dual فترتان (خاص) أو single فترة واحدة (حكومي)',
    morning_start: 'بداية الفترة الصباحية (خاص) بصيغة HH:mm',
    morning_end: 'نهاية الفترة الصباحية (خاص)',
    evening_start: 'بداية الفترة المسائية (خاص فقط)',
    evening_end: 'نهاية الفترة المسائية (خاص فقط)',
    day_start: 'بداية دوام اليوم الواحد (حكومي)',
    day_end: 'نهاية دوام اليوم الواحد (حكومي)',
    governorate: 'المحافظة',
    wilayat: 'الولاية',
    ministry_license_no: 'رقم ترخيص وزارة التنمية الاجتماعية',
    contact_phone: 'هاتف التواصل مع المركز',
    contact_email: 'البريد الإلكتروني للمركز',
    address: 'العنوان التفصيلي',
    status: 'حالة المركز: active / inactive / suspended',
    notes: 'ملاحظات إدارية',
  },
  Specialists: {
    specialist_name: 'اسم الأخصائي / معلم التربية الخاصة',
    specialist_name_ar: 'الاسم بالعربية',
    specialty:
      'التخصص: تربية خاصة · نطق ولغة · علاج وظيفي · علاج طبيعي · نفسي · خدمة اجتماعية · تدخل مبكر',
    professional_email: 'البريد المهني',
    contact_phone: 'هاتف التواصل',
    center_code: 'رمز المركز المرتبط',
    center_record_id: 'معرّف سجل المركز في Airtable',
    duty_shifts: 'نوبات العمل التي يغطيها (صباح / مساء / يوم)',
    status: 'الحالة الوظيفية',
    active_cases: 'عدد الحالات النشطة',
    license_no: 'رقم الترخيص المهني إن وُجد',
    admin_notes: 'ملاحظات إدارية',
    specialist_tutor_token: 'رمز دخول جهاز الأخصائي',
  },
  Students: {
    student_name: 'اسم المستفيد (للأنظمة)',
    student_name_ar: 'اسم المستفيد بالعربية',
    student_id: 'رقم المستفيد داخل المركز',
    national_id: 'الرقم المدني — مفتاح التسجيل الوحيد',
    age: 'العمر بالسنوات',
    date_of_birth: 'تاريخ الميلاد',
    gender: 'الجنس',
    center_code: 'رمز المركز الملتحق به',
    center_record_id: 'معرّف سجل المركز',
    assigned_shift: 'فترة الدوام: صباح / مساء (خاص) أو يوم (حكومي)',
    assigned_class: 'الفصل أو المجموعة',
    assigned_specialist_id: 'معرّف الأخصائي المسؤول',
    diagnosis: 'التشخيص — للأخصائي فقط وليس لولي الأمر',
    presenting_symptoms: 'الأعراض كما يصفها ولي الأمر',
    screening_weights: 'أوزان الفرز الأولي (JSON)',
    parent_phone: 'هاتف ولي الأمر',
    parent_country_code: 'رمز الدولة للهاتف',
    parent_name: 'اسم ولي الأمر',
    status: 'حالة المستفيد في المركز',
    subscription_status: 'حالة الاشتراك / التفعيل',
    plan_code: 'كود الباقة',
    activation_code_used: 'آخر كود تفعيل مستخدم',
    last_payment_at: 'وقت آخر دفعة',
    payment_method: 'طريقة الدفع',
    subscription_expires_at: 'تاريخ انتهاء الاشتراك',
    payment_status: 'حالة الدفع',
    face_biometric: 'بصمة الوجه (JSON مشفر/وصفي)',
    biometric_status: 'حالة اعتماد البصمة',
    biometric_attendance_verified: 'تم التحقق البيومتري للحضور',
    biometric_attendance_at: 'وقت التحقق البيومتري',
    initial_assessment_score: 'درجة التقييم المبدئي',
    comprehensive_assessment_status: 'حالة التقييم الشامل',
    assessment_protocol_json: 'جلسة بروتوكول التقييم الإجرائي (JSON)',
    assessment_protocol_status: 'دورة حياة بروتوكول التقييم',
    active_iep_goals: 'أهداف الخطة الفردية النشطة (JSON)',
    iep_support_severity: 'مستوى الاحتياج الداعم',
    custom_goals_pending: 'أهداف مخصصة بانتظار الاعتماد',
    programmed_goal: 'الهدف الإجرائي الحالي',
    parent_access_token: 'رمز جهاز ولي الأمر',
    child_interactive_token: 'رمز جهاز المستفيد',
    specialist_tutor_token: 'رمز جهاز الأخصائي',
    preferred_destination: 'الوجهة المفضلة بعد الدخول',
    clinical_session_notes: 'ملاحظات الجلسة',
    ai_session_report: 'تقرير الجلسة المختصر',
    zero_point_report: 'تقرير نقطة الصفر',
    academic_progress: 'مؤشر التقدم التربوي',
    behavior_intensity: 'شدة السلوك',
    focus_level: 'مستوى التركيز',
    t_static: 'ثواني الشرود / الثبات',
    improvement_index: 'مؤشر التحسن',
    operating_efficiency: 'كفاءة التشغيل',
    harmony_score: 'درجة التناغم',
    session_fee: 'مستحقات الجلسة',
    enrollment_date: 'تاريخ الالتحاق',
    notes: 'ملاحظات عامة',
  },
  'Access Control': {
    user_name: 'اسم المستخدم',
    user_email: 'البريد الإلكتروني',
    status: 'حالة الحساب',
    permissions: 'الصلاحيات النصية',
    access_level: 'مستوى الوصول: ولي أمر / إدارة / أخصائي / مدير مركز / رقابة',
    access_areas: 'نطاقات الوصول',
    access_token: 'رمز الدخول الخاص',
    center_code: 'رمز المركز المرتبط بالحساب',
    center_record_id: 'معرّف سجل المركز',
    last_login: 'آخر تسجيل دخول',
  },
  'Daily Sessions': {
    session_date: 'تاريخ الجلسة',
    center_code: 'رمز المركز',
    duty_shift: 'فترة الدوام',
    specialty: 'تخصص الجلسة (تربية خاصة / نطق / وظيفي…)',
    specialist_name: 'اسم الأخصائي',
    specialist_record_id: 'معرّف الأخصائي',
    student_name: 'اسم المستفيد',
    student_record_id: 'معرّف المستفيد',
    notes: 'ملاحظات الجلسة',
    claim_status: 'حالة التوثيق: مسودة أو معتمدة',
    sealed_at: 'وقت اعتماد التوثيق',
    specialist_signature: 'توقيع الأخصائي',
    immutable_hash: 'بصمة عدم قابلية التعديل',
    session_sequence: 'تسلسل الجلسة',
    pin_verified: 'تم التحقق بالرمز السري',
    session_fee: 'مستحقات الجلسة',
  },
  'Session Periods': {
    period_key: 'مفتاح الحصة الفريد (مركز::تاريخ::فترة::رقم)',
    center_code: 'رمز المركز',
    center_record_id: 'معرّف المركز',
    session_date: 'تاريخ الحصة',
    duty_shift: 'الفترة: صباح / مساء / يوم',
    period_number: 'رقم الحصة في الجدول',
    start_time: 'وقت البداية HH:mm',
    end_time: 'وقت النهاية HH:mm',
    specialty: 'تخصص الحصة',
    specialist_name: 'اسم الأخصائي / المعلم',
    specialist_record_id: 'معرّف الأخصائي',
    student_name: 'اسم المستفيد',
    student_record_id: 'معرّف المستفيد',
    room_or_hall: 'القاعة أو الغرفة',
    period_status: 'حالة الحصة',
    goal_focus: 'هدف الخطة الفردية / العلاج لهذه الحصة',
    session_notes: 'ملاحظات الحصة',
    recorded_by: 'مسجّل بواسطة',
    sealed_at: 'وقت الاعتماد',
    immutable_hash: 'بصمة عدم قابلية التعديل',
  },
  'Attendance Ledger': {
    ledger_key: 'مفتاح الحضور الفريد',
    center_code: 'رمز المركز',
    center_id: 'معرّف المركز',
    duty_shift: 'فترة الدوام',
    student_record_id: 'معرّف المستفيد',
    student_name: 'اسم المستفيد',
    attendance_date: 'تاريخ الحضور',
    status: 'الحالة: حاضر / غائب / غياب بعذر',
    sealed_at: 'وقت اعتماد السجل',
    immutable_hash: 'بصمة عدم قابلية التعديل',
    recorded_by: 'مسجّل بواسطة',
    biometric_verified: 'تحقق بيومتري',
    note: 'ملاحظة',
  },
  'Goal Evidence': {
    center_code: 'رمز المركز',
    student_record_id: 'معرّف المستفيد',
    goal_id: 'معرّف الهدف',
    goal_label: 'نص الهدف',
    specialty: 'التخصص المرتبط بالدليل',
    evidence_date: 'تاريخ الدليل',
    duty_shift: 'فترة الدوام',
    note: 'ملاحظة الدليل',
    success_percent: 'نسبة النجاح',
    has_photo: 'يوجد مرفق صورة',
    sealed_at: 'وقت الاعتماد',
    immutable_hash: 'بصمة عدم قابلية التعديل',
    teacher_id: 'معرّف المعلم / الأخصائي',
  },
  'Attendance Corrections': {
    center_code: 'رمز المركز',
    student_record_id: 'معرّف المستفيد',
    attendance_date: 'تاريخ الحضور المراد تصحيحه',
    duty_shift: 'فترة الدوام',
    original_status: 'الحالة الأصلية المعتمدة',
    requested_status: 'الحالة المطلوبة',
    reason: 'سبب طلب التصحيح',
    requested_by: 'مقدّم الطلب',
    requested_at: 'وقت الطلب',
    status: 'حالة الطلب: قيد المراجعة / موافق / مرفوض',
    original_hash: 'بصمة السجل الأصلي',
  },
};

/** Table name Arabic labels (for docs / future table description API) */
export const TABLE_LABELS_AR = {
  Centers: 'المراكز',
  Specialists: 'الأخصائيون ومعلمو التربية الخاصة',
  Students: 'المستفيدون',
  'Access Control': 'صلاحيات الدخول',
  'Daily Sessions': 'الجلسات الموثّقة',
  'Session Periods': 'جدول الحصص اليومية',
  'Attendance Ledger': 'سجل الحضور المعتمد',
  'Goal Evidence': 'أدلة تحقق الأهداف',
  'Attendance Corrections': 'طلبات تصحيح الحضور',
};
